import { OrnamentType, OrnamentDef } from '../type/ornament.d';
import ornamentImgUrl from '../assets/ornaments.png';
import ornamentSImgUrl from '../assets/ornaments-s.png';

const ornamentDefs: { [ornamentType in OrnamentType]: OrnamentDef } = {
  standard: {
    image: ornamentImgUrl,
    width: '95px',
    height: '83px',
    imgLeft: 0,
  },
  o1: {
    image: ornamentImgUrl,
    width: '95px',
    height: '83px',
    imgTop: 0,
    imgLeft: 0,
    hint: {
      image: ornamentSImgUrl,
      text: '1. During the scoring, the player with the greatest influence in this column will score an additional +3 VP.',
      width: '240px',
      height: '220px',
      imgWidth: '67px',
      imgHeight: '59px',
      imgTop: 0,
      imgLeft: 0,
    },
  },
  o2: {
    image: ornamentImgUrl,
    width: '95px',
    height: '83px',
    imgTop: 0,
    imgLeft: 95,
    hint: {
      image: ornamentSImgUrl,
      text: '2. Unlike the rest of the columns, this column will be won by the player with the minority of stones of their color. Therefore, if there are 0 white stones and at least 1 black stone, the column will be claimed by the white player.',
      width: '240px',
      height: '220px',
      imgWidth: '67px',
      imgHeight: '59px',
      imgTop: 0,
      imgLeft: 67,
    },
  },
  o3: {
    image: ornamentImgUrl,
    width: '95px',
    height: '83px',
    imgTop: 0,
    imgLeft: 190,
    hint: {
      image: ornamentSImgUrl,
      text: '3. In this column, the gray stones are worth +2 VP instead of -2 VP in the score count.',
      width: '240px',
      height: '220px',
      imgWidth: '67px',
      imgHeight: '59px',
      imgTop: 0,
      imgLeft: 134,
    },
  },
  o4: {
    image: ornamentImgUrl,
    width: '95px',
    height: '83px',
    imgTop: 0,
    imgLeft: 285,
    hint: {
      image: ornamentSImgUrl,
      text: '4. In this column, the gray stones are worth -3 VP instead of -2 VP in the score count.',
      width: '240px',
      height: '220px',
      imgWidth: '67px',
      imgHeight: '59px',
      imgTop: 0,
      imgLeft: 201,
    },
  },
  o5: {
    image: ornamentImgUrl,
    width: '95px',
    height: '83px',
    imgTop: 83,
    imgLeft: 0,
    hint: {
      image: ornamentSImgUrl,
      text: '5. This location\'s bonus temple action can also be activated with gray stones.',
      width: '240px',
      height: '220px',
      imgWidth: '67px',
      imgHeight: '59px',
      imgTop: 59,
      imgLeft: 0,
    },
  },
  o6: {
    image: ornamentImgUrl,
    width: '95px',
    height: '83px',
    imgTop: 83,
    imgLeft: 95,
    hint: {
      image: ornamentSImgUrl,
      text: '6. Choose between this location\'s bonus temple action and the following: move a gray stone from the QUARRY to the TEMPLE (to a different location).',
      width: '240px',
      height: '220px',
      imgWidth: '67px',
      imgHeight: '59px',
      imgTop: 59,
      imgLeft: 67,
    },
  },
  o7: {
    image: ornamentImgUrl,
    width: '95px',
    height: '83px',
    imgTop: 83,
    imgLeft: 190,
    hint: {
      image: ornamentSImgUrl,
      text: '7. This column holds up to 7 stones instead of the usual 5.',
      width: '240px',
      height: '220px',
      imgWidth: '67px',
      imgHeight: '59px',
      imgTop: 59,
      imgLeft: 134,
    },
  },
};

export { ornamentDefs };
