import { OrnamentType, OrnamentDef } from '../type/ornament.d';
import ornamentImgUrl from '../assets/ornaments.png';

const ornamentDefs: { [ornamentType in OrnamentType]: OrnamentDef } = {
  standard: {
    image: ornamentImgUrl,
    width: '95px',
    height: '83px',
    imgLeft: 0,
  },
  o1: {
    image: ornamentImgUrl,
    width: '95px',
    height: '83px',
    imgTop: 0,
    imgLeft: 0,
    hint: {
      image: ornamentImgUrl,
      text: '1. During the scoring, the player with the greatest influence in this column will score an additional +3 VP.',
      width: '320px',
      height: '240px',
      imgWidth: '95px',
      imgHeight: '83px',
      imgTop: 0,
      imgLeft: 0,
    },
  },
  o2: {
    image: ornamentImgUrl,
    width: '95px',
    height: '83px',
    imgTop: 0,
    imgLeft: 95,
    hint: {
      image: ornamentImgUrl,
      text: '2. Unlike the rest of the columns, this column will be won by the player with the minority of stones of their color. Therefore, if there are 0 white stones and at least 1 black stone, the column will be claimed by the white player.',
      width: '320px',
      height: '240px',
      imgWidth: '95px',
      imgHeight: '83px',
      imgTop: 0,
      imgLeft: 95,
    },
  },
  o3: {
    image: ornamentImgUrl,
    width: '95px',
    height: '83px',
    imgTop: 0,
    imgLeft: 190,
    hint: {
      image: ornamentImgUrl,
      text: '3. In this column, the gray stones are worth +2 VP instead of -2 VP in the score count.',
      width: '320px',
      height: '240px',
      imgWidth: '95px',
      imgHeight: '83px',
      imgTop: 0,
      imgLeft: 190,
    },
  },
  o4: {
    image: ornamentImgUrl,
    width: '95px',
    height: '83px',
    imgTop: 0,
    imgLeft: 285,
    hint: {
      image: ornamentImgUrl,
      text: '4. In this column, the gray stones are worth -3 VP instead of -2 VP in the score count.',
      width: '320px',
      height: '240px',
      imgWidth: '95px',
      imgHeight: '83px',
      imgTop: 0,
      imgLeft: 285,
    },
  },
  o5: {
    image: ornamentImgUrl,
    width: '95px',
    height: '83px',
    imgTop: 83,
    imgLeft: 0,
    hint: {
      image: ornamentImgUrl,
      text: '5. This location’s bonus temple action can also be activated with gray stones.',
      width: '320px',
      height: '240px',
      imgWidth: '95px',
      imgHeight: '83px',
      imgTop: 83,
      imgLeft: 0,
    },
  },
  o6: {
    image: ornamentImgUrl,
    width: '95px',
    height: '83px',
    imgTop: 83,
    imgLeft: 95,
    hint: {
      image: ornamentImgUrl,
      text: '6. Choose between this location’s bonus temple action and the following: move a gray stone from the QUARRY to the TEMPLE (to a different location).',
      width: '320px',
      height: '240px',
      imgWidth: '95px',
      imgHeight: '83px',
      imgTop: 83,
      imgLeft: 95,
    },
  },
  o7: {
    image: ornamentImgUrl,
    width: '95px',
    height: '83px',
    imgTop: 83,
    imgLeft: 190,
    hint: {
      image: ornamentImgUrl,
      text: '7. This column holds up to 7 stones instead of the usual 5.',
      width: '320px',
      height: '240px',
      imgWidth: '95px',
      imgHeight: '83px',
      imgTop: 83,
      imgLeft: 190,
    },
  },
};

export { ornamentDefs };
